---
title: Letra Studio
timezone: Europe/Lisbon
collections:
  posts:
    title: Posts
    output: true
defaults:
  - scope:
      path: ""
      type: pages
    values:
      description: false
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "notes"
      type: posts
    values:
      title: ""
      permalink: /:year/:month/:day-:title/

email: hello@letra.studio
description: The one-man studio of João Beleza Freire. Making the Internet a better place, one website at a time.
url: https://letra.studio
baseurl: /letra.studio-jekyll-7811-repro

auth_endpoint: https://indieauth.com/auth
token_endpoint: https://tokens.indieauth.com/token
micropub: /.netlify/functions/micropub

author:
  name: João Beleza Freire
  email: hello@letra.studio
  url: https://letra.studio
  twitter: letrastudio
  avatar: /assets/icons/avatar.jpg
  avatar_small: /assets/icons/avatar-small.jpg
twitter:
  username: letrastudio
logo: /assets/icons/letrastudio-logo.png
social:
  name: Letra Studio
  links:
    - https://twitter.com/letrastudio
    - https://github.com/letrastudio
    - https://instagram.com/joaobelezafreire
    - https://letterboxd.com/joaobfreire

pagination:
  enabled: true

feed_limit: 200
accent_color: "#6495ed"
twitter_username: letrastudio
instagram_username: joaobelezafreire
github_username: letrastudio
letterboxd_username: joaobfreire
lang: en
markdown: kramdown
sass:
  style: compressed
permalink: /:year/:month/:title/
plugins:
- jekyll-paginate-v2
